### ISSUE TITLE
FUSE issue with the 6.2 pipeline CASA version

### ISSUE THREAD

**Issue by mauriliopannella** [ruta-k/CAPTURE-CASA6#11]
Hi, 
I am testing this version of CAPTURE on a L band dataset I acquired few weeks ago. It crushes with the following error:

dlopen(): error loading libfuse.so.2

AppImages require FUSE to run. 
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information

Is this something you have experienced before? I am running CASA  6.2.1-7-pipeline-2021.2.0.128 version. If at useful I am appending here the slurm log file of my run.

Thanks a lot for your help,
Maurilio
[slurm-398027.out.gz](https://github.com/ruta-k/CAPTURE-CASA6/files/10546975/slurm-398027.out.gz)

**Comment by ruta-k** [comment]
Hi Maurilio, Thank you for reporting the error here.  I think the plotms is failing - this is used to make the diagnostic plots. You could comment out the lines using plotms and proceed to use the pipeline. 
Installing the library might solve the issue. Recently I have been using 6.5.2 version of CASA - I have not tried the specific version that you mention so use of a more recent version might also solve the issue.

**Comment by mauriliopannella** [comment]
Hi, thanks for your reply! I'll try with the newer version of CASA and let you know if it works. While I am here may I ask you some advice on how to best tweak the pipeline for L band observations? In particular I have a couple of questions:

1) in the most recent data I got I seem to have an issue with self calibration were things look kind of OK in the area within 13 arcmin from the phase center but they grade pretty quickly between 13 and 20 arcmin. See the attached plot.
![Screenshot from 2023-02-08 13-19-03](https://user-images.githubusercontent.com/100199648/217528482-63992a22-0de5-4410-8408-1b8a0ff677cf.png)

2) the other thing is about some band 4 observations I got on the Spiderweb galaxy which, as you might know, is extremely bright and I am not sure self calibration is helping me as I thought it would. Any suggestion, special tweak for the specific case? 

Thanks a lot for any advice you might have!
And in case you prefer you may also reach me at mpannella@units.it

Best wishes,
Maurilio

**Comment by ruta-k** [comment]
I will respond on your queries over email. Waiting to hear if changing the version or anything else that helped resolve the issue before closing it here.

**Comment by mauriliopannella** [comment]
Hi, installing the libfuse and the new version of CASA did not help to solve the plotting issue. Cannot recall the exact error message but it seemed as if CASA was expecting to find some sort of container. In the end I have to comment out all the plotms commands. Thanks, Maurilio
