### ISSUE TITLE
listscan error under ubuntu 20.04

### ISSUE THREAD

**Issue by mapereztorres** [ruta-k/CAPTURE-CASA6#7]
Dear Ruta,

Thanks a lot for the uGMRT pipeline, which looks really good!

I've tried to run listscan on an .lta data set, on an Ubuntu 20.04 LTS distribution, and I get the following error:

./listscan FILE.lta
$./listscan: error while loading shared libraries: libgfortran.so.3: cannot open shared object file: No such file or directoryI've run
$ sudo apt-get install libgfortran3

and get the following:

Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package libgfortran3 stackoverflow says ubuntu20.04 doesn't use libgfortran3 anymore, but libgfortran5. Indeed, when I run

$ sudo apt-get install libgfortran5

I get the following:

Reading package lists... Done
Building dependency tree
Reading state information... Done
libgfortran5 is already the newest version (10.3.0-1ubuntu1~20.04).
libgfortran5 set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 65 not upgraded.

Maybe you could make available the source files to build up listscan (and maybe gvfits, if there might be a similar issue), or make available executable files for the most recent ubuntu distributions?

Thanks in advance,
Miguel

**Comment by ruta-k** [comment]
Hi Miguel. I dont have an immediate solution to this as I havent used this OS (FITS file can be downloaded from the archive to avoid this step completely!) - thanks for the docker workaround pull request by manuparra to address this issue.

**Comment by ruta-k** [comment]
Hi Miguel,  I will close this issue here as it was resolved with PR of @manuparra (Deployment with docker to use gvfits and listscan without libraries problems). -Ruta

**Comment by manuparra** [comment]
Thanks @ruta-k, you can merge my code, if you want.
